[settings]
always_keep_download = true
experimental = true
plugin_autoupdate_last_check_duration = "0"

[tools]
bun = "1"
java = [ "temurin-21", "graalvm-community-21" ]
node = [ "18", "14" ]
usage = "0"
zig = "0"
